FROM onfinality/subql-node:v5.11.2 AS build
USER root
WORKDIR /app
RUN chown node:node /app
USER node
COPY --chown=node:node . .

RUN yarn install --frozen-lockfile --no-cache
RUN CHAIN_ID="centrifuge" yarn projectgen && yarn codegen && yarn build


FROM onfinality/subql-node:v5.11.2
USER root
WORKDIR /app
RUN chown node:node /app
COPY --from=build --chown=node:node /app/package.json /app/package.json
COPY --from=build --chown=node:node /app/yarn.lock /app/yarn.lock
COPY --from=build --chown=node:node /app/project-generator.sh /app/project-generator.sh
COPY --from=build --chown=node:node /app/schema.graphql /app/schema.graphql
COPY --from=build --chown=node:node /app/dist /app/dist
COPY --from=build --chown=node:node /app/abi /app/abi
COPY --from=build --chown=node:node /app/chains-cfg /app/chains-cfg
COPY --from=build --chown=node:node /app/chains-evm /app/chains-evm
COPY --from=build --chown=node:node /app/docker-entrypoint /app/docker-entrypoint

RUN cp /app/docker-entrypoint /bin/docker-entrypoint

USER node
RUN yarn install --production --frozen-lockfile --no-cache --no-optional && yarn cache clean

# Set Entry point and command
ENTRYPOINT ["/bin/docker-entrypoint"]
CMD []
