#!/bin/sh

export CHAIN_ID=${CHAIN_ID:-centrifuge} 
export NODE_ID=${NODE_ID:-centrifuge}

echo "Starting with parameters:"
echo "CHAIN_ID: ${CHAIN_ID}"
echo "NODE_ID: ${NODE_ID}"

yarn projectgen

if [ $# -eq 0 ]; then
  # If no arguments given, use default command
  set -- /bin/run -f="/app/project-${NODE_ID}.yaml"
elif [ "$1" = "force-clean" ]; then
  # Special case for force-clean command
  set -- /bin/run force-clean -f="/app/project-${NODE_ID}.yaml"
elif [ "${1#-}" != "$1" ]; then
  # If first arg starts with '-', prepend default command
  set -- /bin/run -f="/app/project-${NODE_ID}.yaml" "$@"
else
  # Otherwise use args as-is (allows overriding with direct commands)
  set -- "$@"
fi

exec "$@"
