specVersion: 0.2.0
name: centrifuge-pools
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  endpoint: wss://fullnode.demo.cntrfg.com
  genesisHash: '0x58e48c99021be1b890d2ddf83a547e7d826c8f556736f390f8f96abf5cbe80b8'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handlePoolCreated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: Created
        - handler: handleInvestOrderUpdated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: InvestOrderUpdated
        - handler: handleRedeemOrderUpdated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: RedeemOrderUpdated
        - handler: handleEpochClosed
          kind: substrate/EventHandler
          filter:
            module: pools
            method: EpochClosed
        - handler: handleEpochExecuted
          kind: substrate/EventHandler
          filter:
            module: pools
            method: EpochExecuted