name: SubQL Deploy

# **What it does**: This action deploys to subql

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  subql_deploy_embrio_staging:
    if: ${{ github.repository == 'embrio-tech/centrifuge-subql'}}
    name: Deploy to SubQL (EMBRIO staging)
    strategy:
      matrix:
        chainId: [ centrifuge-devel ] # ADD ARRAY OF CHAINS TO DEPLOY
    uses: ./.github/workflows/subql_deploy_workflow.yaml
    with:
      chainId: ${{ matrix.chainId }}
      projOrg: embrio-tech
      projImage: 'https://explorer.subquery.network/uploads/1660216119964.png'
      deploymentType: primary
      resetProject: true
    secrets:
      accessToken: ${{ secrets.SUBQL_ACCESS_TOKEN }}
    
  subql_deploy_centrifuge_staging:
    if: ${{ github.repository == 'centrifuge/pools-subql' && github.ref_name == 'main' }}
    name: Deploy to SubQL (CENTRIFUGE staging)
    strategy:
      matrix:
        chainId: [ altair ] # ADD ARRAY OF CHAINS TO DEPLOY
    uses: ./.github/workflows/subql_deploy_workflow.yaml
    with:
      chainId: ${{ matrix.chainId }}
      projOrg: centrifuge
      projImage: 'https://explorer.subquery.network/uploads/1660216119964.png'
      deploymentType: primary
      resetProject: true
    secrets:
      accessToken: ${{ secrets.SUBQL_ACCESS_TOKEN }}

  subql_deploy_centrifuge_production:
    if: ${{ github.repository == 'centrifuge/pools-subql' && startsWith(github.ref_name, 'release-') }}
    name: Deploy to SubQL (CENTRIFUGE production)
    strategy:
      matrix:
        chainId: [ altair ] # ADD ARRAY OF CHAINS TO DEPLOY
    uses: ./.github/workflows/subql_deploy_workflow.yaml
    with:
      chainId: ${{ matrix.chainId }}
      projOrg: centrifuge
      deploymentType: stage
      resetProject: false
    secrets:
      accessToken: ${{ secrets.SUBQL_ACCESS_TOKEN }}
