name: SubQL Deploy

# **What it does**: This action deploys to subql

on:
  push:
    branches:
      - main
  pull_request:
  
permissions:
  contents: read
  issues: write

jobs:
  subql_deploy:
    name: Deploy to SubQL
    runs-on: ubuntu-latest
    env:
      SUBQL_ACCESS_TOKEN: ${{ secrets.SUBQL_ACCESS_TOKEN }}
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: 'Install Dependencies'
        run: yarn install
      - name: Create Project
        run: |
          node_modules/@subql/cli/bin/run project:create-project \
          --apiVersion=2 \
          --description="SubQuery API powered by EMBRIO.tech to query Centrifuge chain data for analytics insights on how Centrifuge is unlocking economic opportunity for all by connecting people to borrow and lend money transparently and cost-effectively." \
          --gitRepo="https://github.com/embrio-tech/centrifuge-subql" \
          --org=embrio-tech \
          --project_name=centrifuge-test
      - name: Deploy Version
        run: |
          node_modules/@subql/cli/bin/run deployment:deploy \
          --indexerVersion=1.2.1 \
          --org=embrio-tech \
          --project_name=centrifuge-test \
          --queryVersion=1.2.0 \
          --type=primary
