name: SubQL Deploy

# **What it does**: This action deploys to subql

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
permissions:
  contents: read
  issues: write

jobs:
  subql_deploy:
    name: Deploy to SubQL
    runs-on: ubuntu-latest
    env:
      SUBQL_ACCESS_TOKEN: ${{ secrets.SUBQL_ACCESS_TOKEN }}
      SUBQL_PROJ_ORG: embrio-tech
      SUBQL_PROJ_NAME: centrifuge-subql
      SUBQL_PROJ_DESCRIPTION: "SubQuery API powered by EMBRIO.tech to query Centrifuge chain data for analytics insights on how Centrifuge is unlocking economic opportunity for all by connecting people to borrow and lend money transparently and cost-effectively."
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: 'Install Dependencies'
        run: yarn install
      - name: Create Project
        run: |
          node_modules/@subql/cli/bin/run project:create-project \
          --apiVersion=2 \
          --description="$SUBQL_PROJ_DESCRIPTION" \
          --gitRepo="https://github.com/$GITHUB_REPOSITORY" \
          --org="$SUBQL_PROJ_ORG" \
          --project_name="$SUBQL_PROJ_NAME"
      - name: Deploy Version
        run: |
          IPFSCID=$(subql publish -o -f .)
          node_modules/@subql/cli/bin/run deployment:deploy \
          --indexerVersion=1.6.1 \
          --org="$SUBQL_PROJ_ORG" \
          --project_name="$SUBQL_PROJ_NAME" \
          --queryVersion=1.4.0 \
          --ipfsCID="$IPFSCID" \
          --type=primary
