name: SubQL Deploy
# **What it does**: This action deploys to subql
on:
  push:
    branches:
      - main
      - development
      #- release-*
  workflow_dispatch:

jobs:
  subql_deploy_staging:
    if: ${{ github.ref_name == 'development' }}
    name: Deploy to SubQL (staging)
    strategy:
      matrix:
        chainId: [development, demo] # ADD ARRAY OF CHAINS TO DEPLOY
    uses: ./.github/workflows/subql_deploy_workflow.yaml
    with:
      chainId: ${{ matrix.chainId }}
      projOrg: centrifuge
      projImage: 'https://centrifuge.io/static/bfb7682cb6ed4aa422d9d2c90cd9351a/centrifuge-logomark-black.svg'
      deploymentType: primary
      resetProject: true
    secrets:
      accessToken: ${{ secrets.SUBQL_ACCESS_TOKEN }}
      onfinalityApiKey: ${{ secrets.ONFINALITY_API_KEY }}

  subql_deploy_multichain_staging:
    if: ${{ github.ref_name == 'development' }}
    name: Deploy to SubQL multichain (staging)
    strategy:
      matrix:
        chainId: [demo] # ADD ARRAY OF CHAINS TO DEPLOY
    uses: ./.github/workflows/subql_multi_deploy_workflow.yaml
    with:
      chainId: ${{ matrix.chainId }}
      projOrg: centrifuge
      projImage: 'https://centrifuge.io/static/bfb7682cb6ed4aa422d9d2c90cd9351a/centrifuge-logomark-black.svg'
      deploymentType: primary
      resetProject: true
    secrets:
      accessToken: ${{ secrets.SUBQL_ACCESS_TOKEN }}
      onfinalityApiKey: ${{ secrets.ONFINALITY_API_KEY }}

  subql_deploy_production:
    if: ${{ github.ref_name == 'main' }}
    name: Deploy to SubQL (mainnet)
    strategy:
      matrix:
        chainId: [centrifuge] # ADD ARRAY OF CHAINS TO DEPLOY
    uses: ./.github/workflows/subql_deploy_workflow.yaml
    with:
      chainId: ${{ matrix.chainId }}
      projOrg: centrifuge
      projImage: 'https://centrifuge.io/static/bfb7682cb6ed4aa422d9d2c90cd9351a/centrifuge-logomark-black.svg'
      deploymentType: stage
      resetProject: false
    secrets:
      accessToken: ${{ secrets.SUBQL_ACCESS_TOKEN }}
      onfinalityApiKey: ${{ secrets.ONFINALITY_API_KEY }}

  subql_deploy_multichain_production:
    if: ${{ github.ref_name == 'main' }}
    name: Deploy to SubQL multichain (mainnet)
    strategy:
      matrix:
        chainId: [centrifuge] # ADD ARRAY OF CHAINS TO DEPLOY
    uses: ./.github/workflows/subql_multi_deploy_workflow.yaml
    with:
      chainId: ${{ matrix.chainId }}
      projOrg: centrifuge
      projImage: 'https://centrifuge.io/static/bfb7682cb6ed4aa422d9d2c90cd9351a/centrifuge-logomark-black.svg'
      deploymentType: stage
      resetProject: false
    secrets:
      accessToken: ${{ secrets.SUBQL_ACCESS_TOKEN }}
      onfinalityApiKey: ${{ secrets.ONFINALITY_API_KEY }}
