name: SubQL Deploy

# **What it does**: This action deploys to subql

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  subql_deploy:
    name: Deploy to SubQL
    runs-on: ubuntu-latest
    env:
      CHAIN_ID: centrifuge-devel
      SUBQL_ACCESS_TOKEN: ${{ secrets.SUBQL_ACCESS_TOKEN }}
      SUBQL_PROJ_ORG: embrio-tech
      SUBQL_PROJ_NAME: centrifuge-subql
      SUBQL_PROJ_DESCRIPTION: 'SubQuery API powered by EMBRIO.tech to query Centrifuge chain data for analytics insights on how Centrifuge is unlocking economic opportunity for all by connecting people to borrow and lend money transparently and cost-effectively.'
      SUBQL_PROJ_IMAGE: 'https://explorer.subquery.network/uploads/1660216119964.png'
      #SUBQL_ENDPOINT: wss://fullnode.development.cntrfg.com
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: List directory
        run: yq --help
      - name: Write new project.yaml
        run: echo "${{ steps.project_gen.output.result }}" > project.yaml
      - name: Extract Chain Parameters to ENV
        id: subql_endpoint
        uses: mikefarah/yq@master
        with:
          cmd: yq '.network.endpoint' project.yaml
      - name: Extract subql endpoint to env
        run: echo "SUBQL_ENDPOINT=${{ steps.subql_endpoint.output.result }}" >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Setup Yarn
        run: yarn
      - name: Codegen
        run: yarn codegen
      - name: Version
        run: npx subql --version
      - name: Delete Project
        run: |
          npx subql project:delete-project \
          --org="$SUBQL_PROJ_ORG" \
          --projectName="$SUBQL_PROJ_NAME"
        continue-on-error: true
      - name: Create Project
        run: |
          npx subql project:create-project \
          --apiVersion=2 \
          --description="$SUBQL_PROJ_DESCRIPTION" \
          --gitRepo="https://github.com/$GITHUB_REPOSITORY" \
          --org="$SUBQL_PROJ_ORG" \
          --projectName="$SUBQL_PROJ_NAME" \
          --logoURL="$SUBQL_PROJ_IMAGE"
      - name: Deploy Version
        run: |
          IPFSCID=$(npx subql publish -o -f .)
          sleep 5
          npx subql deployment:deploy \
          --org="$SUBQL_PROJ_ORG" \
          --endpoint="$SUBQL_ENDPOINT" \
          --dict=' ' \
          --projectName="$SUBQL_PROJ_NAME" \
          --ipfsCID="$IPFSCID" \
          --type=primary \
          --indexerVersion="v1.15.1" \
          --queryVersion="v1.9.1"
