on:
  workflow_call:
    inputs:
      chainId:
        required: true
        type: string
      projOrg:
        required: true
        type: string
      projName:
        required: true
        type: string
      projDescription: 
        required: true
        type: string
      projImage:
        required: true
        type: string
      deploymentType:
        required: true
        type: choice
        options: [ primary, stage ]
      resetProject:
        default: false
        type: boolean
      indexerVersion:
        required: true
        type: string
      queryVersion:
        required: true
        type: string
    secrets:
      accessToken:
        required: true


jobs:
  subql_deploy_workflow:
    runs-on: ubuntu-latest
    env:
      CHAIN_ID: ${{ input.chainId }}
      SUBQL_ACCESS_TOKEN: ${{ secrets.accessToken }}
      SUBQL_PROJ_ORG: ${{ input.projOrg }}
      SUBQL_PROJ_NAME: ${{ input.projName }}
      SUBQL_PROJ_DESCRIPTION: ${{ input.projDescription }}
      SUBQL_PROJ_IMAGE: ${{ input.projImage }}
      SUBQL_DEPLOYMENT_TYPE: ${{ input.deploymentType }}
      SUBQL_INDEXER_VERSION: ${{ input.indexerVersion }}
      SUBQL_QUERY_VERSION: ${{ input.queryVersion }}
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Generate new project.yaml
        run: yq ". *= load(\"chains/$CHAIN_ID.yaml\")" chains/base.yaml > project.yaml
      - name: Extract Chain Parameters to ENV
        run: echo "SUBQL_ENDPOINT=$(yq '.network.endpoint' project.yaml)" >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Setup Yarn
        run: yarn install --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: SubQL CLI Version
        run: yarn subql --version
      - name: Publish SubQL version
        run: |
          IPFSCID=$(yarn subql publish -o -f .)
          echo "IPFSCID=$IPFSCID" >> $GITHUB_ENV
          echo "CID: $IPFSCID"
      - name: Delete Project
        if: ${{ input.resetProject }}
        run: |
          yarn subql project:delete-project \
          --org="$SUBQL_PROJ_ORG" \
          --projectName="$SUBQL_PROJ_NAME"
        continue-on-error: true
      - name: Create Project
        run: |
          yarn subql project:create-project \
          --apiVersion=2 \
          --description="$SUBQL_PROJ_DESCRIPTION" \
          --gitRepo="https://github.com/$GITHUB_REPOSITORY" \
          --org="$SUBQL_PROJ_ORG" \
          --projectName="$SUBQL_PROJ_NAME" \
          --logoURL="$SUBQL_PROJ_IMAGE"
      - name: Deploy Version
        run: |
          yarn subql deployment:deploy \
          --org="$SUBQL_PROJ_ORG" \
          --endpoint="$SUBQL_ENDPOINT" \
          --dict=' ' \
          --projectName="$SUBQL_PROJ_NAME" \
          --ipfsCID="$IPFSCID" \
          --type=$SUBQL_DEPLOYMENT_TYPE \
          --disableHistorical \
          --indexerVersion="$SUBQL_INDEXER_VERSION" \
          --queryVersion="$SUBQL_QUERY_VERSION"